project:
  title: "presentation"
  output-dir: "_output"

standalone: true
self-contained: true
slide-level: 2
lang: ru

format:
  beamer:
    toc: true
    toc-title: Содержание
    aspectratio: 169
    pdf-engine: xelatex
    include-in-header:
      - text: |
          \usepackage{polyglossia}
          \setmainlanguage{russian}
          \setotherlanguage{english}
          \usepackage{fontspec}
          \setmainfont{FreeSerif}
          \setsansfont{FreeSans}
          \setmonofont{FreeMono}
    csquotes: true

  revealjs:
    transition: slide
    margin: 0.2
    smaller: true
    slide-number: true
    theme: beige
    logo: _resources/image/logo_rudn.png
